version: 2.1
orbs:
  python: circleci/python@2.0.3

jobs:
  build: # this can be any name you choose
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: download model
          command: wget https://github.com/eyaler/word2vec-slim/raw/master/GoogleNews-vectors-negative300-SLIM.bin.gz

workflows:
  build_and_test: # this can be any name you choose
    jobs:
    - build
